node_js:
- '0.10'
- '0.11'
- '0.12'

language: node_js

deploy:
  provider: npm
  email: contact@duzun.me
  api_key:
    secure: UeTmKdjg0MEmy8iK0ZmlmNww+hytHQoEkh7uhssV2Pizq2sSEKki9m64v7xe35Kwk38TcbMvrZkwtim/ZnZt1JJ2LOw8Ogz88OVviqAfkHOe2VRH8SrP3NpRFGFWLZ0JmvKGkvCLiDkLHiz+vSegUXDPwyGdpS932lyxJ5U3ntE=
  on:
    tags: true
    repo: duzun/jAJAX
